export const products = [
  {
    id: 1,
    name: 'Luxe Arctic Marble',
    category: 'Floor Tiles',
    price: 12367,
    stock: 'In Stock',
    color: 'White',
    size: '24" x 24"',
    material: 'Polished Marble',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    description: 'A luminous white marble tile for elegant floor installations and refined living spaces.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      { label: 'Finish', value: 'Polished Marble' },
      { label: 'Size', value: '24" x 24"' },
      { label: 'Color', value: 'White' },
      { label: 'Material', value: 'Polished Marble' },
      { label: 'Usage', value: 'Floor' },
      { label: 'Edge Style', value: 'Straight' },
    ],
    rating: 4.8,
    reviews: 124,
    availability: 'In Stock',
    finish: 'High Shine',
    reviewsList: [
      {
        name: 'Cameron Grey',
        rating: 5,
        comment: 'The tile feels incredibly premium and the polished finish made our kitchen glow. Worth every penny.',
      },
      {
        name: 'Sofia Hayes',
        rating: 4,
        comment: 'Beautiful material and fast delivery. The only thing I wish is that the sample shipment arrived sooner.',
      },
    ],
  },
  {
    id: 2,
    name: 'Noir Velvet Slate',
    category: 'Wall Tiles',
    price: 9296,
    stock: 'In Stock',
    color: 'Black',
    size: '12" x 24"',
    material: 'Textured Slate',
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=900&q=80',
    description: 'Deep charcoal slate with natural texture for dramatic accent walls and showers.',
    images: [
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      { label: 'Finish', value: 'Textured Slate' },
      { label: 'Size', value: '12" x 24"' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'Textured Slate' },
      { label: 'Usage', value: 'Wall' },
      { label: 'Edge Style', value: 'Straight' },
    ],
    rating: 4.7,
    reviews: 98,
    availability: 'In Stock',
    finish: 'Matte',
    reviewsList: [
      {
        name: 'Maya Cole',
        rating: 5,
        comment: 'This slate tile instantly elevated our bathroom design. The finish is gorgeous and feels sturdy.',
      },
      {
        name: 'Jordan Lee',
        rating: 4,
        comment: 'Subtle texture and premium look—would love more sizes in this color.',
      },
    ],
  },
  {
    id: 3,
    name: 'Sahara Terracotta',
    category: 'Bathroom Tiles',
    price: 7885,
    stock: 'Low Stock',
    color: 'Terracotta',
    size: '18" x 18"',
    material: 'Glazed Ceramic',
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=900&q=80',
    description: 'Warm terracotta that brings earthy luxury to spa bathrooms and powder rooms.',
    images: [
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      { label: 'Finish', value: 'Glazed Ceramic' },
      { label: 'Size', value: '18" x 18"' },
      { label: 'Color', value: 'Terracotta' },
      { label: 'Material', value: 'Glazed Ceramic' },
      { label: 'Usage', value: 'Bathroom' },
      { label: 'Edge Style', value: 'Straight' },
    ],
    rating: 4.4,
    reviews: 64,
    availability: 'Low Stock',
    finish: 'Glaze',
    reviewsList: [
      {
        name: 'Avery Smith',
        rating: 4,
        comment: 'The terracotta tone is rich and warm, perfect for our spa-inspired bathroom.',
      },
    ],
  },
  {
    id: 4,
    name: 'Coastal Pearl Porcelain',
    category: 'Outdoor Tiles',
    price: 10707,
    stock: 'In Stock',
    color: 'Pearl',
    size: '24" x 48"',
    material: 'Porcelain',
    image: 'https://images.unsplash.com/photo-1586023492128-5a0b7bffc8dc?auto=format&fit=crop&w=900&q=80',
    description: 'Durable porcelain with a soft pearlescent finish crafted for patios and terraces.',
    images: [
      'https://images.unsplash.com/photo-1586023492128-5a0b7bffc8dc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      { label: 'Finish', value: 'Pearlescent' },
      { label: 'Size', value: '24" x 48"' },
      { label: 'Color', value: 'Pearl' },
      { label: 'Material', value: 'Porcelain' },
      { label: 'Usage', value: 'Outdoor' },
      { label: 'Edge Style', value: 'Straight' },
    ],
    rating: 4.6,
    reviews: 79,
    availability: 'In Stock',
    finish: 'Pearl Sheen',
    reviewsList: [
      {
        name: 'Harper Jones',
        rating: 5,
        comment: 'Perfect outdoor tile for our terrace. It is elegant and durable for the weather.',
      },
    ],
  },
  {
    id: 5,
    name: 'Jet Noir Granite',
    category: 'Floor Tiles',
    price: 13446,
    stock: 'In Stock',
    color: 'Black',
    size: '36" x 36"',
    material: 'Honed Granite',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80',
    description: 'Bold granite floor tile with silky honed finish for high-end minimal interiors.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      { label: 'Finish', value: 'Honed Granite' },
      { label: 'Size', value: '36" x 36"' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'Honed Granite' },
      { label: 'Usage', value: 'Floor' },
      { label: 'Edge Style', value: 'Straight' },
    ],
    rating: 4.9,
    reviews: 110,
    availability: 'In Stock',
    finish: 'Honed',
    reviewsList: [
      {
        name: 'Elliot Reed',
        rating: 5,
        comment: 'This granite tile is the perfect anchor for our luxury living room.',
      },
    ],
  },
  {
    id: 6,
    name: 'Ivory Linen Mosaic',
    category: 'Bathroom Tiles',
    price: 6474,
    stock: 'In Stock',
    color: 'Ivory',
    size: '2" x 2" Mosaic',
    material: 'Glass Mosaic',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80',
    description: 'Soft ivory mosaic tiles that create luminous surfaces with subtle texture.',
    images: [
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      { label: 'Finish', value: 'Glass Mosaic' },
      { label: 'Size', value: '2" x 2" Mosaic' },
      { label: 'Color', value: 'Ivory' },
      { label: 'Material', value: 'Glass Mosaic' },
      { label: 'Usage', value: 'Bathroom' },
      { label: 'Edge Style', value: 'Straight' },
    ],
    rating: 4.5,
    reviews: 81,
    availability: 'In Stock',
    finish: 'Shimmer',
    reviewsList: [
      {
        name: 'Riley Adams',
        rating: 4,
        comment: 'Beautiful mosaic finish with great texture and depth.',
      },
    ],
  },
];

export const categories = ['All', 'Floor Tiles', 'Wall Tiles', 'Bathroom Tiles', 'Outdoor Tiles'];
export const colors = ['White', 'Black', 'Terracotta', 'Pearl', 'Ivory'];
export const sizes = ['12" x 24"', '18" x 18"', '24" x 24"', '24" x 48"', '36" x 36"'];
export const materials = ['Polished Marble', 'Textured Slate', 'Glazed Ceramic', 'Porcelain', 'Honed Granite', 'Glass Mosaic'];

export const getProductById = (id) => products.find((product) => product.id === Number(id));
export const productKeys = {
  all: ["products"],
};
