export const AppRoutes = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:productId',
  CATEGORIES: '/categories',
  ABOUT: '/about',
  SETTINGS: '/settings',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/cart',
  CHECKOUT: '/checkout',
  CUSTOMER_DASHBOARD: '/customer/dashboard',
  CUSTOMER_ORDERS: '/customer/orders',
  WISHLIST: '/customer/wishlist',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_INVENTORY: '/admin/inventory',
  ADMIN_INVOICES: '/admin/invoices',
  ADMIN_ANALYTICS: '/admin/analytics',
  AI_VISUALIZER: '/ai-visualizer',
  DESIGN_EXPLORER: '/design-explorer',
  SEARCH: '/search',
  NOTIFICATIONS: '/notifications',
  NOT_FOUND: '*',
};
